import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { addDays, getWeekStart } from "@/lib/workScheduleConfig";
import { REQUEST_STATUS_LABELS, REQUEST_STATUS_STYLES, REQUEST_TYPE_LABELS } from "@/lib/workScheduleRequestLabels";

export default function AdminRequestsPanel({ weekStart, setWeekStart }) {
  const [status, setStatus] = useState("PENDING"); const [worker, setWorker] = useState("ALL"); const [responses, setResponses] = useState({});
  const queryClient = useQueryClient();
  const { data: requests = [] } = useQuery({ queryKey: ["workScheduleRequests"], queryFn: async () => (await base44.functions.invoke("manageWorkScheduleRequests", { action: "admin_list" })).data.requests || [] });
  const weekEnd = addDays(weekStart, 6);
  const weekRequests = requests.filter((request) => { const start = request.start_date || request.date || ""; const end = request.end_date || start; return start && start <= weekEnd && end >= weekStart; });
  const workers = [...new Map(weekRequests.map((request) => [request.worker_profile_id || request.worker_id, request.worker_name])).entries()].filter(([id]) => id);
  const visible = weekRequests.filter((request) => (status === "ALL" || request.status === status) && (worker === "ALL" || (request.worker_profile_id || request.worker_id) === worker));
  const update = async (request, nextStatus = request.status) => { await base44.functions.invoke("manageWorkScheduleRequests", { action: "admin_update", request_id: request.id, status: nextStatus, admin_response: responses[request.id] ?? request.admin_response ?? "" }); queryClient.invalidateQueries({ queryKey: ["workScheduleRequests"] }); };
  return <section className="rounded-2xl border bg-white p-4 shadow-sm" dir="rtl">
    <div className="flex flex-wrap items-center justify-between gap-2 mb-4"><h2 className="text-lg font-bold">בקשות</h2><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setWeekStart(addDays(weekStart, -7))}>שבוע קודם</Button><Button size="sm" variant="outline" onClick={() => setWeekStart(getWeekStart())}>השבוע</Button><Button size="sm" variant="outline" onClick={() => setWeekStart(addDays(weekStart, 7))}>שבוע הבא</Button></div></div>
    <div className="flex gap-2 mb-4"><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-md border px-3 py-2 text-sm"><option value="ALL">כל הסטטוסים</option>{["PENDING", "APPROVED", "REJECTED", "CANCELLED"].map((value) => <option key={value} value={value}>{REQUEST_STATUS_LABELS[value]}</option>)}</select><select value={worker} onChange={(e) => setWorker(e.target.value)} className="rounded-md border px-3 py-2 text-sm"><option value="ALL">כל העובדים</option>{workers.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b text-right text-slate-500">{["עובד", "סוג בקשה", "תאריך / טווח", "שעות", "הודעה", "סטטוס", "תשובת מנהל", "פעולות"].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{visible.map((request) => <tr key={request.id} className="border-b align-top"><td className="p-2 font-semibold">{request.worker_name}</td><td className="p-2">{REQUEST_TYPE_LABELS[request.request_type] || request.request_type}</td><td className="p-2">{request.start_date || request.date}{request.end_date && request.end_date !== request.start_date ? ` – ${request.end_date}` : ""}</td><td className="p-2" dir="ltr">{request.start_time || request.end_time ? `${request.start_time || ""}–${request.end_time || ""}` : "—"}</td><td className="p-2 max-w-56 whitespace-pre-wrap">{request.message || request.requested_change_text || request.notes}</td><td className="p-2"><span className={`rounded-full border px-2 py-0.5 text-xs ${REQUEST_STATUS_STYLES[request.status]}`}>{REQUEST_STATUS_LABELS[request.status]}</span></td><td className="p-2"><Textarea rows={2} value={responses[request.id] ?? request.admin_response ?? ""} onChange={(e) => setResponses({ ...responses, [request.id]: e.target.value })} /></td><td className="p-2"><div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" onClick={() => update(request, "APPROVED")}>אשר</Button><Button size="sm" variant="outline" onClick={() => update(request, "REJECTED")}>דחה</Button><Button size="sm" variant="outline" onClick={() => update(request)}>הוסף תגובה</Button>{request.status !== "CANCELLED" && <Button size="sm" variant="ghost" onClick={() => update(request, "CANCELLED")}>סמן כבטלה</Button>}</div></td></tr>)}</tbody></table>{!visible.length && <div className="py-8 text-center text-sm text-slate-400">אין בקשות להצגה</div>}</div>
  </section>;
}